AWSTemplateFormatVersion: '2010-09-09'
Description: 
  "My first EC2 instance from yaml file"

Mappings:
  AMIRegionMap:
    "us-east-1": 
      "AmazonLinux2": "ami-06a0cd9728546d178"
      "Ubuntu2004LTS": "ami-007855ac798b5175e"
    "us-west-2": 
      "AmazonLinux2": "ami-06a0cd9728546d178"
      "Ubuntu2004LTS": "ami-007855ac798b5175e"


Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: myKey
      InstanceType: "t2.micro"
      SubnetId: "subnet-0a47cfcb41e84b4bb"
      SecurityGroupIds: 
        - "sg-0a932f9eed14f14b8"
      Tags: 
        - Key: "Name"
          Value: "myEC2Instance"
        - Key: "Launched By"
          Value: "CloudFormation"
      ImageId: !FindInMap [ AMIRegionMap, "us-east-1", AmazonLinux2 ]

      